---
- hosts: asa
  gather_facts: false


  tasks:
  - name: get facts from device
    napalm_get_facts:
      hostname={{ inventory_hostname }}
      username={{ username }}
      dev_os={{ os }}
      password={{ password }}
      filter='facts,interfaces,bgp_neighbors'
    register: result
