---
- hosts: all
  gather_facts: false


  tasks:
  - name: get facts from device
    napalm_get_facts:
      hostname={{ ansible_ssh_host }}
      username={{ remote_user }}
      dev_os={{ ansible_network_os }}
      password={{ ansible_ssh_pass }}
      filter='facts,interfaces,bgp_neighbors'
    register: napalm_facts
    
  - debug: var=napalm_facts
